name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        sudo apt-get -y update
        sudo apt-get install -y python3-pip python3-gi gir1.2-gtk-3.0 libgtk-3-dev libgirepository1.0-dev
        pip3 install --upgrade pip
        pip3 install cairosvg pycodestyle jsonschema pygobject
        
    - name: Test
      run: |
        sh ./tests/pycodestyle.sh
        python3 ./tests/schema.py
        python3 ./tests/db_entry.py
        python3 ./tests/icons_entry.py
        python3 ./tests/ordered_db.py
        python3 ./tests/icon_cache.py
